### ISSUE TITLE
imaging_plane unused

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/axel-lab-to-nwb#15]
https://github.com/ben-dichter-consulting/axel-lab-to-nwb/blob/68f203d77ab7d6f65c67c7144d772d42197aca81/axel_lab_to_nwb/conversion_module.py#L85-L94

PyCharm automatically detects this

**Comment by luiztauffer** [comment]
you mean allocating it into a variable?
I'll remove it!
