### ISSUE TITLE
plot_rois should be optional arg

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/axel-lab-to-nwb#9]
Sometimes I like to use dictionaries if I am passing optional args to an inner function, like the way seaborn does [here](https://seaborn.pydata.org/generated/seaborn.jointplot.html), but it looks like in this case `plot_rois` would be better as a normal optional arg.

https://github.com/ben-dichter-consulting/axel-lab-to-nwb/blob/3f71dbb1378abedcfdeccb5233e615cafd9d8dfd/axel_lab_to_nwb/conversion_module.py#L21-L43

**Comment by luiztauffer** [comment]
This is following the standard for conversion functions, which are being used by the conversion scripts of all labs and also makes it sure the GUI interface works
The source files: source_paths
The destination file: f_nwb
The metadata: metadata
Any extra thing lab-specific: **kwargs

**Comment by bendichter** [comment]
Why would be have the standard for conversion functions? Why wouldn't we make the optional args explicit?

**Comment by luiztauffer** [comment]
To make sure GUI, for example, will be able to call the conversion function from all labs.
Here's how the GUI's thread to run any user-supplied conversion module is implemented:

```python
class ConversionFunctionThread(QtCore.QThread):
    def run(self):
        mod_file = self.parent.conversion_module_path
        spec = importlib.util.spec_from_file_location(os.path.basename(mod_file).strip('.py'), mod_file)
        conv_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(conv_module)
        metadata = self.parent.read_metadata_from_form()
        conv_module.conversion_function(source_paths=self.parent.source_paths,
                                        f_nwb=self.parent.lin_nwb_file.text(),
                                        metadata=metadata,
                                        **self.parent.kwargs_fields)
```
